name: My  workflow
on: fork
jobs:
    _job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v7

        - name: Welcome message
          run: echo "My  Github Actions Job"

        - name: list files
          run: ls
                
        



