name: My  workflow
<<<<<<< HEAD
on: fork
=======
on: workflow_dispatch
>>>>>>> b6990a54a846b11d9c4f841a8657a82af5d52325

jobs:
    _job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v7

        - name: Welcome message
          run: echo "My  Github Actions Job"

        - name: list files
          run: ls
                
        



