name : MULTIPLE_JOBS
on:
    push
jobs:
    build_job_1:
        
        runs-on: ubuntu-latest
        steps:
        - name: Install cowsay 
          run: sudo apt-get update && sudo apt-get install -y cowsay

        - name: Execute cowsay CMD
          run: cowsay -f dragon "BHAG BHAG DKBOSE..." >> dragon.txt

        - name: sleep for 5 sec
          run: sleep 3

        - name: upload the created artifacts
          uses: actions/upload-artifact@v3
          with:
            name : dragon-text-file
            path: dragon.txt
        archive: false

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        - name: sleep for another 1 sec
          run: sleep 1

        - name: Download the artifact
          uses: actions/download-artifact@v3
          with:
            name: dragon.txt # corresponds to the uploaded file name

        - name: Test file exists
          run: grep -i "BHAG" dragon.txt
          
    deploy_job:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
        - name: Download the artifact
          uses: actions/download-artifact@v8
          with:
            name: dragon.txt  

        - name: Read file
          run: cat dragon.txt

        - name: Deploy
          run: echo" DEPLOYING.... "
            
            



